### ISSUE TITLE
Announcement draft

### ISSUE THREAD

**Issue by nopara73** [nopara73/ZeroLink#27]
https://medium.com/@nopara73/introducing-zerolink-the-bitcoin-fungibility-framework-dc5338086198

- [x] Fix typos
- [x] Explain how it works in more detail

**Comment by SamouraiDev** [comment]
Announcement draft should be kept as short as possible with very few, if any, details. Otherwise it runs the risk of becoming outdated with needs for revision. Details will be found on github page.

**Comment by nopara73** [comment]
I am wondering if we even need a medium announcement. Maybe just stick with the GitHub?

**Comment by SamouraiDev** [comment]
I think that the Medium announcement is useful in terms of visibility if kept to a minimum that requires no updating afterwards.

**Comment by nopara73** [comment]
Finished.
