### ISSUE TITLE
Coinjoin and equal outs

### ISSUE THREAD

**Issue by AdamISZ** [nopara73/ZeroLink#4]
It can be seen as academic but perhaps isn't:

> When multiple participants add inputs to a common CJ transaction and some of the outputs have the same value no one can tell which input was intended to fund which of these outputs.

It's quite possible to do coinjoin with all-non-equal output amounts and one could dream up use cases for it; e.g. (A, B) could pay (C, D) and go through the trouble of coordinating a coinjoin just for the sake of confusing analysis.

It's important IMV since every sense in which the "all inputs are co-owned" is invalidated aids Bitcoin's fungibility.

You might want to add a note (although it's not a contradiction to your doc) that Bitcoin has this property inherently, it's not an add-on invented by Greg Maxwell, it's just that he was the first one to explain it clearly and make use of it. Admittedly most reading the doc would not be confused on that point, but I bet a few would (a lot of other people don't know it).

**Comment by nopara73** [comment]
I was happy I could take care of explaining CoinJoin in one sentence. It seems like it's not entirely correct after all.  

I made some modifications, based on your suggestions: https://github.com/nopara73/ZeroLink/commit/73dabada7147a50a07b49f3d5fba2727a9884398  
  
Please reopen the issue if it is still incorrect.
