### ISSUE TITLE
Z

### ISSUE THREAD

**Issue by nopara73** [nopara73/ZeroLink#47]

**Comment by wintercooled** [comment]
Could we set a round initially to be time based? e.g. as many as we can get in a couple of hours maybe? (or something like that)
So we'd start off saying 'a round is open, please stay connected for x minutes'. After that amount of time we begin the round with however many clients we have. We could broadcast the number of connected clients in the round and if people were not happy with the count they could pull out before it began. That way people know how long they need to stay connected up front. If we do it connected client count based they have no idea how long they need to stay connected until we hit that number.
