### ISSUE TITLE
Typing numeric value into mixing Amount doesnt work as expected. Windows 10

### ISSUE THREAD

**Issue by ghhelperau** [nopara73/ZeroLink#57]
Windows 10.

When on mixing page, and you go to type "8" in the "Amount (BTC)" field, no matter the numeric value you enter, it increases the amount already in the field by 0.1 BTC.

When value is 0.4, and you type 9, the value changes to 0.5.

Its as if the numeric values are being treated as an "arrow up" keypress.

**Comment by nopara73** [comment]
I moved this conversation to HiddenWallet repo: https://github.com/nopara73/HiddenWallet/issues/126
