### ISSUE TITLE
Review BIP126

### ISSUE THREAD

**Issue by nopara73** [nopara73/ZeroLink#8]
https://github.com/bitcoin/bips/blob/master/bip-0126.mediawiki

**Comment by nopara73** [comment]
@SamouraiDev We need not concern ourselves with this, right? Post-mix wallets never join inputs and always have 2 outputs. And as I understand it, this BIP is tackling the same problem, just in a less strict, less effective, but more user friendly manner.  

> When a Bitcoin transaction contains inputs that reference previous transaction outputs sent to different Bitcoin addresses, personally identifiable information of the user will leak into the blockchain in an uncontrolled manner.

**Comment by SamouraiDev** [comment]
Correct. In order to respect that post-mix wallet rule, BIP126 cannot be used within this framework. BIP126 is effective, but outside the scope of this discussion.
