### ISSUE TITLE
Stealth Addresses And Reusable Payment Codes

### ISSUE THREAD

**Issue by nopara73** [nopara73/ZeroLink#9]
@SamouraiDev I was thinking what is the best way to incorporate Stealth Addresses And Reusable Payment Codes. What do you think about this workflow?  

In ZeroLink I have some notes that what should be explored and improved in the future, like these ones:  
-> Of course distributed systems are more resilient, therefore distribution should certainly be an interest of future research.  
-> Elimination of the Tor dependency should be an interest of future research.  

How about you add a new section under the Introduction about Stealth Addreses and Reusable Payment Codes?  

1. Describe the problem: Every time a CJ round is aborted, pre-mix wallets must register a new CJ output, cannot reuse already used ones. If the post-mix wallet is different from pre-mix wallet, to generate new addresses an extpubkey must be provided. In case of a successful and sophisticated persistent DoS attack post-mix wallets must monitor their keys fairly deep.  
2. Tell Reusable Payment Codes are the solution.  
3. Tell they are not part of ZeroLink, because their complexity does not justify its benefits for now and it would prevent other wallets implementing a pre-mix wallet addition. But this should definitely be considered as a future improvement.  
4. Description:  
Describe what you feel is necessary for readers to grasp the idea, then present a model of how to make CoinJoin transactions using payment codes instead of extpubkeys.

**Comment by SamouraiDev** [comment]
https://github.com/nopara73/ZeroLink/pull/15
